######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 24 21:25:40 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += time.cpp time2.cpp
